package Payments;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.net.URL;
import javax.swing.JPanel;
import javax.swing.UIManager;
import com.formdev.flatlaf.themes.*;

/**
 *
 * @author USER
 */
public class PaymentUI extends javax.swing.JFrame {

    /**
     * Creates new form PaymentUI
     */
    public PaymentUI() {
        initComponents();

        setTitle("Speedy Seat");

        qrCodePanel = new qrCodePanel();
        onlinePaymentPanel = new onlinePaymentPanel();
        payAtCounterPanel = new payAtCounterPanel();

        cardLayout = new CardLayout();

        mainPanel = new JPanel(cardLayout);

        mainPanel.add(qrCodePanel, "qrCodePanel");
        mainPanel.add(onlinePaymentPanel, "onlinePaymentPanel");
        mainPanel.add(payAtCounterPanel, "payAtCounterPanel");

        methodPanel.add(mainPanel, java.awt.BorderLayout.CENTER);

        qrCode.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        onlineBanking.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        payAtCounter.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        qrCode.setOpaque(true);
        qrCode.setBackground(new Color(102,102,102));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundedPanel1 = new RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        dateShowtime = new javax.swing.JLabel();
        movieName = new javax.swing.JLabel();
        movieGenre = new javax.swing.JLabel();
        runtime = new javax.swing.JLabel();
        theatre = new javax.swing.JLabel();
        sound = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        seat = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        roundedPanel2 = new RoundedPanel();
        qrCode = new javax.swing.JLabel();
        onlineBanking = new javax.swing.JLabel();
        payAtCounter = new javax.swing.JLabel();
        methodPanel = new RoundedPanel();
        roundedPanel3 = new RoundedPanel();
        roundedPanel4 = new RoundedPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));

        roundedPanel1.setBackground(new java.awt.Color(51, 51, 51));
        roundedPanel1.setPreferredSize(new java.awt.Dimension(1162, 327));

        URL imgURL = getClass().getResource("/Icon/Test_Poster.jpg");
        if (imgURL != null) {
            jLabel1.setIcon(new javax.swing.ImageIcon(imgURL));
        } else {
            System.err.println("Image not found: " + "/Icon/Test_Poster.jpg");
        }

        try {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Test_Poster.jpg")));
        } catch (NullPointerException e) {
            System.err.println("Image not found: " + e.getMessage());
        }


        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Test_Poster.jpg")));// C:\Users\USER\Desktop\ISAD\speedyseat1\test\src\main\Icon
        jLabel1.setText("jLabel1");

        dateShowtime.setFont(new java.awt.Font("Segue UI", 0, 14)); // NOI18N
        dateShowtime.setForeground(new java.awt.Color(153, 204, 255));
        dateShowtime.setText("17 October 2024   |  18:00");

        movieName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        movieName.setForeground(new java.awt.Color(255, 255, 255));
        movieName.setText("Look Back");

        movieGenre.setBackground(new java.awt.Color(255, 255, 255));
        movieGenre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        movieGenre.setForeground(new java.awt.Color(255, 255, 255));
        movieGenre.setText("Action, Drama, Romance");

        runtime.setForeground(new java.awt.Color(255, 255, 255));
        runtime.setText("60 min");

        theatre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        theatre.setForeground(new java.awt.Color(255, 255, 255));
        theatre.setText("Theatre 7");

        sound.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sound.setForeground(new java.awt.Color(255, 255, 255));
        sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sound.png"))); // NOI18N
        sound.setText("ENG");

        subtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subtitle.setForeground(new java.awt.Color(255, 255, 255));
        subtitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/subtitle.png"))); // NOI18N
        subtitle.setText("TH");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("|");

        seat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        seat.setForeground(new java.awt.Color(255, 255, 255));
        seat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/seat.png"))); // NOI18N
        seat.setText("M7");

        price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setText("Price: 160 ฿");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("|");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/display.png"))); // NOI18N
        jLabel5.setText("IMAX");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
                roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(dateShowtime)
                                                        .addComponent(movieName)
                                                        .addComponent(movieGenre)
                                                        .addComponent(runtime)
                                                        .addComponent(theatre)
                                                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                                                                .addComponent(sound)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(subtitle)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel4)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel5)))
                                                .addContainerGap(229, Short.MAX_VALUE))
                                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                                                .addComponent(seat)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(price)
                                                .addGap(74, 74, 74))))
        );
        roundedPanel1Layout.setVerticalGroup(
                roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(dateShowtime)
                                                .addGap(18, 18, 18)
                                                .addComponent(movieName)
                                                .addGap(18, 18, 18)
                                                .addComponent(movieGenre)
                                                .addGap(18, 18, 18)
                                                .addComponent(runtime)
                                                .addGap(18, 18, 18)
                                                .addComponent(theatre)
                                                .addGap(18, 18, 18)
                                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(sound)
                                                        .addComponent(subtitle)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5))
                                                .addGap(18, 18, 18)
                                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(seat)
                                                        .addComponent(price))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        roundedPanel2.setBackground(new java.awt.Color(51, 51, 51));
        roundedPanel2.setPreferredSize(new java.awt.Dimension(200, 200));

        qrCode.setBackground(new java.awt.Color(102, 102, 102));
        qrCode.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        qrCode.setForeground(new java.awt.Color(255, 255, 255));
        qrCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/qr-code.png"))); // NOI18N
        qrCode.setText("QR Code");
        qrCode.setIconTextGap(30);
        qrCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qrCodeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                qrCodeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                qrCodeMousePressed(evt);
            }
        });

        onlineBanking.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        onlineBanking.setForeground(new java.awt.Color(255, 255, 255));
        onlineBanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/banking.png"))); // NOI18N
        onlineBanking.setText("Online Banking");
        onlineBanking.setIconTextGap(30);
        onlineBanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onlineBankingMouseClicked(evt);
            }
        });

        payAtCounter.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        payAtCounter.setForeground(new java.awt.Color(255, 255, 255));
        payAtCounter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/counter.png"))); // NOI18N
        payAtCounter.setText("Pay at Counter");
        payAtCounter.setIconTextGap(30);
        payAtCounter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payAtCounterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
                roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel2Layout.createSequentialGroup()
                                .addContainerGap(57, Short.MAX_VALUE)
                                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(onlineBanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(qrCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(payAtCounter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54))
        );
        roundedPanel2Layout.setVerticalGroup(
                roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(roundedPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(qrCode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(onlineBanking)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(payAtCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(17, Short.MAX_VALUE))
        );

        methodPanel.setBackground(new java.awt.Color(51, 51, 51));
        methodPanel.setMinimumSize(new java.awt.Dimension(300, 700));
        methodPanel.setPreferredSize(new java.awt.Dimension(300, 700));
        methodPanel.setLayout(new java.awt.BorderLayout());

        roundedPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
                roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 200, Short.MAX_VALUE)
        );
        roundedPanel3Layout.setVerticalGroup(
                roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 363, Short.MAX_VALUE)
        );

        methodPanel.add(roundedPanel3, java.awt.BorderLayout.LINE_START);

        roundedPanel4.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout roundedPanel4Layout = new javax.swing.GroupLayout(roundedPanel4);
        roundedPanel4.setLayout(roundedPanel4Layout);
        roundedPanel4Layout.setHorizontalGroup(
                roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 200, Short.MAX_VALUE)
        );
        roundedPanel4Layout.setVerticalGroup(
                roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 363, Short.MAX_VALUE)
        );

        methodPanel.add(roundedPanel4, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(methodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                                        .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(methodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 363, Short.MAX_VALUE)
                                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void qrCodeMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

    }

    private void qrCodeMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

    }

    private void qrCodeMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        qrCode.setOpaque(true);
        qrCode.setBackground(new Color(102,102,102));

        onlineBanking.setOpaque(true);
        onlineBanking.setBackground(new Color(51, 51, 51));

        payAtCounter.setOpaque(true);
        payAtCounter.setBackground(new Color(51, 51, 51));

        cardLayout.show(mainPanel, "qrCodePanel");
    }

    private void onlineBankingMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        onlineBanking.setOpaque(true);
        onlineBanking.setBackground(new Color(102,102,102));

        qrCode.setOpaque(true);
        qrCode.setBackground(new Color(51, 51, 51));

        payAtCounter.setOpaque(true);
        payAtCounter.setBackground(new Color(51, 51, 51));

        cardLayout.show(mainPanel, "onlinePaymentPanel");
    }

    private void payAtCounterMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        payAtCounter.setOpaque(true);
        payAtCounter.setBackground(new Color(102,102,102));

        qrCode.setOpaque(true);
        qrCode.setBackground(new Color(51, 51, 51));

        onlineBanking.setOpaque(true);
        onlineBanking.setBackground(new Color(51, 51, 51));

        cardLayout.show(mainPanel, "payAtCounterPanel");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PaymentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel dateShowtime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private RoundedPanel methodPanel;
    private javax.swing.JLabel movieGenre;
    private javax.swing.JLabel movieName;
    private javax.swing.JLabel onlineBanking;
    private javax.swing.JLabel payAtCounter;
    private javax.swing.JLabel qrCode;
    private RoundedPanel roundedPanel1;
    private RoundedPanel roundedPanel2;
    private RoundedPanel roundedPanel3;
    private RoundedPanel roundedPanel4;
    private javax.swing.JLabel runtime;
    private javax.swing.JLabel seat;
    private javax.swing.JLabel sound;
    private javax.swing.JLabel subtitle;
    private javax.swing.JLabel theatre;
    // End of variables declaration
    private CardLayout cardLayout;
    private JPanel qrCodePanel;
    private JPanel onlinePaymentPanel;
    private JPanel payAtCounterPanel;
    private JPanel mainPanel;
}
